include: ['_pages', 'assets']

collections:
  Teaching:
    output: true

kramdown:
  input: GFM

# Theme settings
theme: jekyll-theme-minimal

# Site settings
title: HUANG, Jia-Ping

description: Jia-Ping HUANG is a lecturer at Shenzhen University.

google_analytics: UA-135009652-1

logo: /assets/img/photo.png

show_downloads: 'false'

#baseurl: ""
#url: "https://huangjp.com"
#github_username: huangjp28
#name: HUANG, Jia-Ping's Official Website

# Build settings
#sass:
#  sass_dir: _sass
